sudo: required
services:
  - docker

before_install:
  - docker build -t jay/react-test -f ./client/Dockerfile.dev .

script:
  docker run -e CI=true jay/react-test npm test

after_success:
  - docker build -t jay/multi-client ./client
  - docker build -t jay/multi-nginx ./nginx
  - docker build -t jay/multi-server ./server
  - docker build -t jay/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passoword-stdin
  - docker push jay/multi-client
  - docker push jay/multi-nginx
  - docker push jay/multi-server
  - docker push jay/multi-worker