sudo: required
services:
  - docker

before_install:
  - docker build -t jay100/react-test -f ./client/Dockerfile.dev ./client

script:
  docker run -e CI=true jay100/react-test npm test

after_success:
  - docker build -t jay100/multi-client ./client
  - docker build -t jay100/multi-nginx ./nginx
  - docker build -t jay100/multi-server ./server
  - docker build -t jay100/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jay100/multi-client
  - docker push jay100/multi-nginx
  - docker push jay100/multi-server
  - docker push jay100/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-ap-south-1-142488468220
  bucket_path: docker_multi
  on: 
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

  
